#!/bin/bash
echo "Point group scalar still generator starting"

# -------------------------------------------------------
# get the script arguments
BUILD_FOLDER="$1"
NTHREADS="$2"
RAYSHADE="$3"
TMP_FOLDER="$BUILD_FOLDER"/tmp

#
# loop through all point groups
#
for FILE in pg_*_still.ray; do 
	echo 'starting scalar still image for point group file ' $FILE `date`
	if [ -e $FILE ]; then 
		echo $FILE >$TMP_FOLDER/play$FILE
		sed -i back "s/pg_//" $TMP_FOLDER/play$FILE
		sed -i back "s/\.ray//" $TMP_FOLDER/play$FILE
		read short <$TMP_FOLDER/play$FILE
		rm $TMP_FOLDER/play$FILE
		rm $TMP_FOLDER/play"$FILE"back
		$RAYSHADE <$FILE >$TMP_FOLDER/pg_$short.mtv  2>/dev/null
		convert -colorspace RGB -auto-level $TMP_FOLDER/pg_$short.mtv $BUILD_FOLDER/pg_$short\_scalar\.jpeg
		rm -f $TMP_FOLDER/pg_$short.mtv
	fi
done
# collect all the jpegs into a tar-ball
CURDIR=`pwd`
cd $BUILD_FOLDER
rm -f scalar_stills.tar
tar -cf scalar_stills.tar *.jpeg
gzip scalar_stills.tar
rm -f *.jpeg
echo "Point group scalar still generator quitting"
exit
