#!/bin/bash
echo "Point group axial vector movies generator starting"
# -------------------------------------------------------
# get the script arguments
RENDER_FILE="$1"
if [ -f $RENDER_FILE ]; then
  . $RENDER_FILE
else
    echo "$RENDER_FILE not found; exiting"
    exit
fi

#
# each subfolder corresponds to one point group, so loop through all folders
#
for FILE in *; do 
	if [ -d $FILE ]; then 
		./doone_movie $FILE $RENDER_FILE
	fi
done
# 
CURDIR=`pwd`
cd $BUILD_FOLDER
/bin/rm -f axial_movies.tar axial_movies.tar.gz
tar -cf axial_movies.tar *.mp4
gzip axial_movies.tar
/bin/rm *.mp4
cd $CURDIR
#
# That's it !
#
echo "Point group axial vector movies generator quitting"
exit

