#!/bin/sh
echo "Point group axial vector stills generator starting"
#
# each subfolder corresponds to one point group, so loop through all folders
#
# first we need to do the 32 gray groups, since they have a different color scheme than all the others
LISTGRAY="listgray"
while IFS= read -r FILE
do
	./doone_still $FILE
done <"$LISTGRAY"

# then we do the remaining 90 groups






# 
# combine all jpeg images into an archive
#
for FILE in *; do
	if [ -d $FILE ]; then
		if [ -e $FILE/$FILE-1.jpeg ]; then 
			cp $FILE/$FILE-*.jpeg .
		fi
	fi
done
tar -cf axial_stills.tar *.jpeg
gzip axial_stills.tar
/bin/rm *.jpeg
#
# That's it !
#
echo "Point group axial vector stills generator quitting"
exit
