#!/bin/sh
echo "Point group stereo generator starting"
#
# loop through all point groups
#
for FILE in pg_*.ray; do 
	echo 'starting stereo images for point group file ' $FILE `date`
	if [ -e $FILE ]; then 
		echo $FILE >/tmp/play
		sed -i s/pg_// /tmp/play
		sed -i s/\.ray// /tmp/play
		read short </tmp/play
		rayshade -l <$FILE >/tmp/pg.mtv  2>/dev/null
		convert -colorspace RGB /tmp/pg.mtv pg_$short\_left\.jpeg
		rayshade -r <$FILE >/tmp/pg.mtv  2>/dev/null
		convert -colorspace RGB /tmp/pg.mtv pg_$short\_right\.jpeg
		rm -f /tmp/pg.mtv
	fi
done
#
# That's it !
#
rm -f stereo_pg.tar
tar -cf stereo_pg.tar pg_*.jpeg
gzip stereo_pg.tar
rm -f pg_*.jpeg
echo "Point group stereo generator quitting"
exit
