#!/bin/bash
echo "Point group polar vector stills generator starting"
# -------------------------------------------------------
# get the script arguments
BUILD_FOLDER="$1"
NTHREADS="$2"
POVRAY="$3"
POVRAYinclude="$4"
TMP_FOLDER="$BUILD_FOLDER"/tmp

#
# each subfolder corresponds to one point group, so loop through all folders
#
for FILE in *; do 
	if [ -d $FILE ]; then 
		./doone_still $FILE $BUILD_FOLDER $NTHREADS $POVRAY $POVRAYinclude
	fi
done
# 
CURDIR=`pwd`
cd $BUILD_FOLDER
/bin/rm -f polar_stills.tar polar_stills.tar.gz
tar -cf polar_stills.tar *.jpeg
gzip polar_stills.tar
/bin/rm *.jpeg
cd $CURDIR
#
# That's it !
#
echo "Point group polar vector stills generator quitting"
exit
