#!/bin/bash
echo "Point group polar vector stills generator starting"
# -------------------------------------------------------
# get the script arguments
RENDER_FILE="$2"
if [ -f $RENDER_FILE ]; then
  . $RENDER_FILE
else
    echo "$RENDER_FILE not found; exiting"
    exit
fi

#
# each subfolder corresponds to one point group, so loop through all folders
#
for FILE in *; do 
	if [ -d $FILE ]; then 
		./doone_still $FILE $RENDER_FILE
	fi
done
# 
CURDIR=`pwd`
cd $BUILD_FOLDER
/bin/rm -f polar_stills.tar polar_stills.tar.gz
tar -cf polar_stills.tar *.jpeg
gzip polar_stills.tar
/bin/rm *.jpeg
cd $CURDIR
#
# That's it !
#
echo "Point group polar vector stills generator quitting"
exit
