#!/bin/bash
echo "Start polar movie for point group " $1 `date`

# -------------------------------------------------------
# get the script arguments
PGDIR="$1"
RENDER_FILE="$2"
if [ -f $RENDER_FILE ]; then
  . $RENDER_FILE
else
    echo "$RENDER_FILE not found; exiting"
    exit
fi
FILE=pg_"$PGDIR"_movie\.pov

# test to make sure that the requested number of threads is <= the available number
MAXTHREADS=`sysctl -n hw.ncpu`   # need to check for OS... this one will only work on Mac OS X
if [ $NTHREADS -gt $MAXTHREADS ]
  then 
    NTHREADS="$MAXTHREADS"
fi



cd $PGDIR

echo "Input_File_Name=$FILE" >povray.ini
echo "Output_File_Name=$FRAMES_FOLDER/"$PGDIR"_movie.png" >>povray.ini
echo "+L$POVRAYinclude" >>povray.ini
echo "+W$MOVIE_SIZE +H$MOVIE_SIZE" >>povray.ini
echo "Initial_Clock=0" >>povray.ini
echo "Initial_Frame=0" >>povray.ini
echo "Final_Clock=$N_FRAMES" >>povray.ini
echo "Final_Frame=$N_FRAMES" >>povray.ini
echo "Frame_Step=$FRAME_STEP" >>povray.ini
echo "Work_Threads=$NTHREADS" >>povray.ini

$POVRAY povray.ini 2>/dev/null
$FFMPEG -i $FRAMES_FOLDER/"$PGDIR"_movie%03d.png -y -c:v libx264 -pix_fmt yuv420p $BUILD_FOLDER/polar_"$PGDIR".mp4 >/dev/null 2>/dev/null

rm -f $FRAMES_FOLDER/"$PGDIR"_movie*\.png
rm -f povray.ini
cd ../
exit
