#!/bin/bash
echo "Point group pseudoscalar still generator starting"

RENDER_FILE="$1"
if [ -f $RENDER_FILE ]; then
  . $RENDER_FILE
else
    echo "$RENDER_FILE not found; exiting"
    exit
fi

#
# loop through all point groups
#
for FILE in pg_*_still.pov; do 
	echo 'starting pseduoscalar still image for point group file ' $FILE `date`
	if [ -e $FILE ]; then 
		echo $FILE >$TMP_FOLDER/play
		sed -i back "s/_still\.pov//" $TMP_FOLDER/play
		read short <$TMP_FOLDER/play
		rm $TMP_FOLDER/play
		rm $TMP_FOLDER/playback
		echo "Input_File_Name=$FILE" >povray.ini
		echo "Output_File_Name=$BUILD_FOLDER/"$short"_still.png" >>povray.ini
		echo "+L$POVRAYinclude" >>povray.ini
		echo "+W$STILL_SIZE +H$STILL_SIZE" >>povray.ini
		echo "Initial_Clock=0" >>povray.ini
		echo "Initial_Frame=0" >>povray.ini
		echo "Final_Clock=0" >>povray.ini
		echo "Final_Frame=0" >>povray.ini
		echo "Work_Threads=$NTHREADS" >>povray.ini

		$POVRAY povray.ini 2>/dev/null
		$CONVERT -colorspace RGB -auto-level $BUILD_FOLDER/$short\_still\.png  $BUILD_FOLDER/$short\_pseudoscalar_still\.jpeg
		rm -f $BUILD_FOLDER/$short\_still\.png
	fi
done
rm povray.ini
# collect all the jpegs into a tar-ball
CURDIR=`pwd`
cd $BUILD_FOLDER
rm -f pseudoscalar_stills.tar
tar -cf pseudoscalar_stills.tar *.jpeg
gzip pseudoscalar_stills.tar
rm -f *.jpeg
echo "Point group pseudoscalar still generator quitting"
exit
