#!/bin/sh
echo "Point group pseudoscalar still generator starting"
#
# loop through all point groups
#
for FILE in pg_*_still.ray; do 
	echo 'starting pseudoscalar still image for point group file ' $FILE `date`
	if [ -e $FILE ]; then 
		echo $FILE >/tmp/play
		sed -i s/pg_// /tmp/play
		sed -i s/\_still.ray// /tmp/play
		read short </tmp/play
		rayshade  <$FILE >/tmp/pg.mtv  2>/dev/null
		convert -colorspace RGB /tmp/pg.mtv pseudoscalar_$short\.jpeg
		rm -f /tmp/pg.mtv
	fi
done
rm -f pseudoscalar_stills.tar
tar -cf pseudoscalar_stills.tar *.jpeg
gzip pseudoscalar_stills.tar
rm -f *.jpeg
echo "Point group pseudoscalar still generator quitting"
exit
