#!/bin/bash
echo "Point group pseudoscalar movie generator starting"

# -------------------------------------------------------
# get the script arguments
# -------------------------------------------------------
# get the script arguments
BUILD_FOLDER="$1"
NTHREADS="$2"
POVRAY="$3"
POVRAYinclude="$4"
FFMPEG="$5"
TMP_FOLDER="$BUILD_FOLDER"/tmp
FRAMES_FOLDER="$BUILD_FOLDER"/frames

#
# loop through all point groups
#
for FILE in pg_*_movie.pov; do 
	echo 'starting pseudoscalar movie for point group file ' $FILE `date`
	if [ -e $FILE ]; then 
		echo $FILE >$TMP_FOLDER/play
		sed -i back "s/_movie\.pov//" $TMP_FOLDER/play
		read short <$TMP_FOLDER/play
		rm $TMP_FOLDER/play
		rm $TMP_FOLDER/playback
		echo "Input_File_Name=$FILE" >povray.ini
		echo "Output_File_Name=$FRAMES_FOLDER/"$short"_movie.png" >>povray.ini
		echo "+L$POVRAYinclude" >>povray.ini
		echo "+W800 +H800" >>povray.ini
		echo "Initial_Clock=0" >>povray.ini
		echo "Initial_Frame=0" >>povray.ini
		echo "Final_Clock=359" >>povray.ini
		echo "Final_Frame=359" >>povray.ini
		echo "Work_Threads=$NTHREADS" >>povray.ini
		$POVRAY povray.ini 2>/dev/null
		$FFMPEG -i $FRAMES_FOLDER/"$short"_movie%03d.png -y -c:v libx264 -pix_fmt yuv420p $BUILD_FOLDER/"$short"_pseudoscalar.mp4 >/dev/null 2>/dev/null
		/bin/rm -f $FRAMES_FOLDER/*.png povray.ini
	fi
done
CURDIR=`pwd`
cd $BUILD_FOLDER
rm -f pseudoscalar_movies.tar
tar -cf pseudoscalar_movies.tar pg_*_pseudoscalar.mp4
gzip pseudoscalar_movies.tar
rm -f *.mp4
echo "Point group pseudoscalar movie generator quitting"
exit
