#!/bin/bash
echo "raw conversion to PoVray format starting"

#
# loop through all point groups
#
for FILE in pg_*.ray; do 
	echo 'starting conversion for point group file ' $FILE 
	if [ -e $FILE ]; then 
		echo $FILE >play$FILE
		sed -i back "s/\.ray//" play$FILE
		read short <play$FILE
		rm play$FILE
		rm play"$FILE"back
		if [ -e $short.png ]; then 
		echo ""
		else 
		echo "// Copyright (c) 2008-2018, Marc De Graef Research Group/Carnegie Mellon University" >$short.pov
		echo "// BSD2 license, see license.txt file accompanying this distribution" >>$short.pov
		echo "" >>$short.pov
		echo "// Persistence of Vision Ray Tracer Scene Description File" >>$short.pov
		echo "// File: $short.pov" >>$short.pov
		echo "// Vers: 3.7" >>$short.pov
		echo "// Desc: pov file for raw rendering of point group $short" >>$short.pov
		echo "// Date: 09/19/2018" >>$short.pov
		echo "// Auth: Marc De Graef" >>$short.pov
		echo "#version 3.7;" >>$short.pov
		echo "global_settings {" >>$short.pov
  		echo "	assumed_gamma 1.0" >>$short.pov
  		echo "	max_trace_level 10" >>$short.pov
		echo "}" >>$short.pov
		echo "" >>$short.pov
		echo "#include \"colors.inc\"" >>$short.pov
		echo "#include \"metals.inc\"" >>$short.pov
		echo "#include \"../inc/mpg-view.inc\"" >>$short.pov
		echo "#include \"../inc/mpg-macros.inc\"" >>$short.pov
		cat $FILE >>$short.pov
		sed -i back "s/#include \"preface.ray\"//" $short.pov
		sed -i back "s/#include \"tail.ray\"//" $short.pov
		sed -i back "s/name point_group/#declare point_group=/" $short.pov
		sed -i back "s/list/union {/" $short.pov
		sed -i back "s/end/}/" $short.pov
		sed -i back "s/object/object { /" $short.pov
		sed -i back "s/refaxis/cartesian() }/" $short.pov
		sed -i back "s/mirrorplane/mirrorplane() }/" $short.pov
		sed -i back "s/axis_two/axis_two() }/" $short.pov
		sed -i back "s/axis_three/axis_three() }/" $short.pov
		sed -i back "s/axis_four/axis_four() }/" $short.pov
		sed -i back "s/axis_five/axis_five() }/" $short.pov
		sed -i back "s/axis_six/axis_six() }/" $short.pov
		sed -i back "s/sympoint/sympoint() }/" $short.pov
		sed -i back "s/1 0 0 /x*/" $short.pov
		sed -i back "s/0 1 0 /z*/" $short.pov
		sed -i back "s/0 0 1 /y*/" $short.pov
		sed -i back "s/1.0 0.0 0.0 /x*/" $short.pov
		sed -i back "s/0.0 1.0 0.0 /z*/" $short.pov
		sed -i back "s/0.0 0.0 1.0 /y*/" $short.pov
		rm $short.povback
		echo "" >>$short.pov
		echo "object { point_group }" >>$short.pov
		fi
	fi
done
exit
