#!/bin/bash
echo "Point group raw generator starting"

# -------------------------------------------------------
# get the script arguments
BUILD_FOLDER="$1"
NTHREADS="$2"
POVRAY="$3"
POVRAYinclude="$4"
TMP_FOLDER="$BUILD_FOLDER"/tmp

#
# loop through all point groups
#
for FILE in pg_*.pov; do 
	echo 'starting raw image for point group file ' $FILE `date`
	if [ -e $FILE ]; then 
		echo $FILE >$TMP_FOLDER/play
		sed -i back "s/\.pov//" $TMP_FOLDER/play
		read short <$TMP_FOLDER/play
		rm $TMP_FOLDER/play
		rm $TMP_FOLDER/playback
		echo "Input_File_Name=$FILE" >povray.ini
		echo "Output_File_Name=$BUILD_FOLDER/"$short"_raw.png" >>povray.ini
		echo "+L$POVRAYinclude" >>povray.ini
		echo "+W1280 +H1280" >>povray.ini
		echo "Initial_Clock=0" >>povray.ini
		echo "Initial_Frame=0" >>povray.ini
		echo "Final_Clock=0" >>povray.ini
		echo "Final_Frame=0" >>povray.ini
		echo "Work_Threads=$NTHREADS" >>povray.ini

		$POVRAY povray.ini 2>/dev/null
		convert -colorspace RGB -auto-level $BUILD_FOLDER/$short\_raw\.png  $BUILD_FOLDER/$short\_raw\.jpeg
		rm -f $BUILD_FOLDER/$short\_raw\.png
	fi
done
# collect all the jpegs into a tar-ball
CURDIR=`pwd`
cd $BUILD_FOLDER
rm -f raw_pg.tar
tar -cf raw_pg.tar *.jpeg
gzip raw_pg.tar
rm -f *.jpeg
cd $CURDIR
cd ../
echo "Point group raw generator quitting"
exit
