#!/bin/bash
echo "Start special positions movie for point group 4/mmm " `date`

RENDER_FILE="$1"
if [ -f $RENDER_FILE ]; then
  . $RENDER_FILE
else
    echo "$RENDER_FILE not found; exiting"
    exit
fi

#
# loop through all frames
#
short=pg_4overmmm
echo "Input_File_Name="$short"_sp1.pov" >povray.ini
echo "Output_File_Name=$FRAMES_FOLDER/frame1_.png" >>povray.ini
echo "+L$POVRAYinclude" >>povray.ini
echo "+W$MOVIE_SIZE +H$MOVIE_SIZE" >>povray.ini
echo "Initial_Clock=0" >>povray.ini
echo "Initial_Frame=0" >>povray.ini
echo "Final_Clock=9" >>povray.ini
echo "Final_Frame=9" >>povray.ini
echo "Frame_Step=1" >>povray.ini
echo "Work_Threads=$NTHREADS" >>povray.ini
$POVRAY povray.ini 2>/dev/null
echo "Input_File_Name="$short"_sp2.pov" >povray.ini
echo "Output_File_Name=$FRAMES_FOLDER/frame2_.png" >>povray.ini
echo "+L$POVRAYinclude" >>povray.ini
echo "+W$MOVIE_SIZE +H$MOVIE_SIZE" >>povray.ini
echo "Initial_Clock=0" >>povray.ini
echo "Initial_Frame=0" >>povray.ini
echo "Final_Clock=9" >>povray.ini
echo "Final_Frame=9" >>povray.ini
echo "Frame_Step=1" >>povray.ini
echo "Work_Threads=$NTHREADS" >>povray.ini
$POVRAY povray.ini 2>/dev/null
echo "Input_File_Name="$short"_sp3.pov" >povray.ini
echo "Output_File_Name=$FRAMES_FOLDER/frame3_.png" >>povray.ini
echo "+L$POVRAYinclude" >>povray.ini
echo "+W$MOVIE_SIZE +H$MOVIE_SIZE" >>povray.ini
echo "Initial_Clock=0" >>povray.ini
echo "Initial_Frame=0" >>povray.ini
echo "Final_Clock=9" >>povray.ini
echo "Final_Frame=9" >>povray.ini
echo "Frame_Step=1" >>povray.ini
echo "Work_Threads=$NTHREADS" >>povray.ini
$POVRAY povray.ini 2>/dev/null
echo "Input_File_Name="$short"_sp4.pov" >povray.ini
echo "Output_File_Name=$FRAMES_FOLDER/frame4_.png" >>povray.ini
echo "+L$POVRAYinclude" >>povray.ini
echo "+W$MOVIE_SIZE +H$MOVIE_SIZE" >>povray.ini
echo "Initial_Clock=0" >>povray.ini
echo "Initial_Frame=0" >>povray.ini
echo "Final_Clock=9" >>povray.ini
echo "Final_Frame=9" >>povray.ini
echo "Frame_Step=1" >>povray.ini
echo "Work_Threads=$NTHREADS" >>povray.ini
$POVRAY povray.ini 2>/dev/null
echo "Input_File_Name="$short"_sp5.pov" >povray.ini
echo "Output_File_Name=$FRAMES_FOLDER/frame5_.png" >>povray.ini
echo "+L$POVRAYinclude" >>povray.ini
echo "+W$MOVIE_SIZE +H$MOVIE_SIZE" >>povray.ini
echo "Initial_Clock=0" >>povray.ini
echo "Initial_Frame=0" >>povray.ini
echo "Final_Clock=9" >>povray.ini
echo "Final_Frame=9" >>povray.ini
echo "Frame_Step=1" >>povray.ini
echo "Work_Threads=$NTHREADS" >>povray.ini
$POVRAY povray.ini 2>/dev/null
rm -f povray.ini

mv $FRAMES_FOLDER/frame1_0.png $FRAMES_FOLDER/frame00.png
mv $FRAMES_FOLDER/frame1_1.png $FRAMES_FOLDER/frame01.png
mv $FRAMES_FOLDER/frame1_2.png $FRAMES_FOLDER/frame02.png
mv $FRAMES_FOLDER/frame1_3.png $FRAMES_FOLDER/frame03.png
mv $FRAMES_FOLDER/frame1_4.png $FRAMES_FOLDER/frame04.png
mv $FRAMES_FOLDER/frame1_5.png $FRAMES_FOLDER/frame05.png
mv $FRAMES_FOLDER/frame1_6.png $FRAMES_FOLDER/frame06.png
mv $FRAMES_FOLDER/frame1_7.png $FRAMES_FOLDER/frame07.png
mv $FRAMES_FOLDER/frame1_8.png $FRAMES_FOLDER/frame08.png
mv $FRAMES_FOLDER/frame1_9.png $FRAMES_FOLDER/frame09.png
mv $FRAMES_FOLDER/frame2_0.png $FRAMES_FOLDER/frame10.png
mv $FRAMES_FOLDER/frame2_1.png $FRAMES_FOLDER/frame11.png
mv $FRAMES_FOLDER/frame2_2.png $FRAMES_FOLDER/frame12.png
mv $FRAMES_FOLDER/frame2_3.png $FRAMES_FOLDER/frame13.png
mv $FRAMES_FOLDER/frame2_4.png $FRAMES_FOLDER/frame14.png
mv $FRAMES_FOLDER/frame2_5.png $FRAMES_FOLDER/frame15.png
mv $FRAMES_FOLDER/frame2_6.png $FRAMES_FOLDER/frame16.png
mv $FRAMES_FOLDER/frame2_7.png $FRAMES_FOLDER/frame17.png
mv $FRAMES_FOLDER/frame2_8.png $FRAMES_FOLDER/frame18.png
mv $FRAMES_FOLDER/frame2_9.png $FRAMES_FOLDER/frame19.png
mv $FRAMES_FOLDER/frame3_0.png $FRAMES_FOLDER/frame20.png
mv $FRAMES_FOLDER/frame3_1.png $FRAMES_FOLDER/frame21.png
mv $FRAMES_FOLDER/frame3_2.png $FRAMES_FOLDER/frame22.png
mv $FRAMES_FOLDER/frame3_3.png $FRAMES_FOLDER/frame23.png
mv $FRAMES_FOLDER/frame3_4.png $FRAMES_FOLDER/frame24.png
mv $FRAMES_FOLDER/frame3_5.png $FRAMES_FOLDER/frame25.png
mv $FRAMES_FOLDER/frame3_6.png $FRAMES_FOLDER/frame26.png
mv $FRAMES_FOLDER/frame3_7.png $FRAMES_FOLDER/frame27.png
mv $FRAMES_FOLDER/frame3_8.png $FRAMES_FOLDER/frame28.png
mv $FRAMES_FOLDER/frame3_9.png $FRAMES_FOLDER/frame29.png
mv $FRAMES_FOLDER/frame4_0.png $FRAMES_FOLDER/frame30.png
mv $FRAMES_FOLDER/frame4_1.png $FRAMES_FOLDER/frame31.png
mv $FRAMES_FOLDER/frame4_2.png $FRAMES_FOLDER/frame32.png
mv $FRAMES_FOLDER/frame4_3.png $FRAMES_FOLDER/frame33.png
mv $FRAMES_FOLDER/frame4_4.png $FRAMES_FOLDER/frame34.png
mv $FRAMES_FOLDER/frame4_5.png $FRAMES_FOLDER/frame35.png
mv $FRAMES_FOLDER/frame4_6.png $FRAMES_FOLDER/frame36.png
mv $FRAMES_FOLDER/frame4_7.png $FRAMES_FOLDER/frame37.png
mv $FRAMES_FOLDER/frame4_8.png $FRAMES_FOLDER/frame38.png
mv $FRAMES_FOLDER/frame4_9.png $FRAMES_FOLDER/frame39.png
mv $FRAMES_FOLDER/frame5_0.png $FRAMES_FOLDER/frame40.png
mv $FRAMES_FOLDER/frame5_1.png $FRAMES_FOLDER/frame41.png
mv $FRAMES_FOLDER/frame5_2.png $FRAMES_FOLDER/frame42.png
mv $FRAMES_FOLDER/frame5_3.png $FRAMES_FOLDER/frame43.png
mv $FRAMES_FOLDER/frame5_4.png $FRAMES_FOLDER/frame44.png
mv $FRAMES_FOLDER/frame5_5.png $FRAMES_FOLDER/frame45.png
mv $FRAMES_FOLDER/frame5_6.png $FRAMES_FOLDER/frame46.png
mv $FRAMES_FOLDER/frame5_7.png $FRAMES_FOLDER/frame47.png
mv $FRAMES_FOLDER/frame5_8.png $FRAMES_FOLDER/frame48.png
mv $FRAMES_FOLDER/frame5_9.png $FRAMES_FOLDER/frame49.png

$FFMPEG -i $FRAMES_FOLDER/frame%02d.png -y -c:v libx264 -pix_fmt yuv420p $BUILD_FOLDER/specialpositions.mp4 >/dev/null 2>/dev/null
/bin/rm -f $FRAMES_FOLDER/*.png
CURDIR=`pwd`
cd $BUILD_FOLDER
rm -f specialpositions.tar.gz
tar -cf specialpositions.tar specialpositions.mp4
gzip specialpositions.tar
rm -f *.mp4
echo "Point group special positions movie generator quitting"


exit
